spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://**.**.**.**:3306/freetime?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT&autoReconnect=true&failOverReadOnly=false
  mail:
    #发送邮件服务器
    host: smtp.qq.com
    #发送邮件的邮箱地址
    username: **@**.com
    #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    password: *************
    # 发送邮件的地址，和上面username一致
    from: **@**.com
    properties:
      mail:
        smtp:
          post:465